apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kindswap-backend
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme }}
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    {{- if .Values.ingress.certArn }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certArn }}
    {{- end }}
    {{- if .Values.ingress.vpnCidr }}
    alb.ingress.kubernetes.io/inbound-cidrs: {{ .Values.ingress.vpnCidr }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: kindswap-backend
                port:
                  number: 80
