{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: kindswap-backend
    environment: {{ .Values.environment }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::916994818641:role/kindswap-backend-{{ .Values.environment }}-irsa
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
