# Staging Environment Override Values
environment: staging

image:
  repository: ""
  tag: latest
  pullPolicy: Always

replicaCount:
  min: 1
  max: 3

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

serviceAccount:
  create: true
  name: kindswap-backend
  annotations: {}

nodeSelector: {}

ingress:
  enabled: true
  host: stg.kindswap.world
  scheme: internal
  vpnCidr: ""
  certArn: arn:aws:acm:us-east-1:916994818641:certificate/f39e16e4-6479-4f02-8999-f600a495736c

hpa:
  targetCPUPercent: 70

pgPool:
  max: 50
