environment: production
image:
  repository: 916994818641.dkr.ecr.us-east-1.amazonaws.com/kindswap-backend
  tag: bacdd26c287bf130bf6c3be75bec6019b882967b  # Latest working commit
  pullPolicy: Always

replicaCount:
  min: 2
  max: 10

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 512Mi

serviceAccount:
  create: true
  name: kindswap-backend
  annotations: {}

nodeSelector: {}

ingress:
  enabled: true
  host: kindswap.world
  scheme: internet-facing
  vpnCidr: ""
  certArn: arn:aws:acm:us-east-1:916994818641:certificate/f39e16e4-6479-4f02-8999-f600a495736c

hpa:
  targetCPUPercent: 70

pgPool:
  max: 40
