environment: production
image:
  repository: ""
  tag: latest
  pullPolicy: Always

replicaCount:
  min: 1
  max: 10

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 512Mi

serviceAccount:
  create: true
  name: kindswap-backend
  annotations: {}

nodeSelector: {}

ingress:
  enabled: true
  host: kindswap.world
  scheme: internet-facing
  vpnCidr: ""

hpa:
  targetCPUPercent: 70

pgPool:
  max: 40
