{{- if and .Values.serviceAccount.create (eq .Values.serviceAccount.name "kindswap-backend") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: kindswap-backend
    environment: {{ .Values.environment }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::916994818641:role/kindswap-backend-{{ if eq .Values.environment "production" }}prod{{ else }}{{ .Values.environment }}{{ end }}-irsa
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
