apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kindswap-admin-frontend.fullname" . }}
  labels:
    {{- include "kindswap-admin-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ index .Values.replicaCount .Values.environment }}
  selector:
    matchLabels:
      {{- include "kindswap-admin-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kindswap-admin-frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
