apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kindswap-admin-frontend.fullname" . }}
  labels:
    {{- include "kindswap-admin-frontend.labels" . | nindent 4 }}
  annotations:
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme }}
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.connection.keep_alive.enabled=true
    {{- if .Values.ingress.certArn }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certArn }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    {{- else }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    {{- end }}
spec:
  ingressClassName: alb
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "kindswap-admin-frontend.fullname" . }}
            port:
              number: 80
