apiVersion: v1
kind: Service
metadata:
  name: {{ include "kindswap-admin-frontend.fullname" . }}
  labels:
    {{- include "kindswap-admin-frontend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "kindswap-admin-frontend.selectorLabels" . | nindent 4 }}
