replicaCount:
  production: 2
  staging: 1
  dev: 1

image:
  repository: ""  # Will be overridden by Helm upgrade --set image.repository
  tag: latest

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

environment: dev
ingress:
  enabled: true
  host: admin.production.kindswap.world
  scheme: internet-facing
  certArn: arn:aws:acm:us-east-1:916994818641:certificate/f39e16e4-6479-4f02-8999-f600a495736c