export enum AdminPermission {
  FEE_CONFIG = 'FEE_CONFIG',
  CONTRIBUTIONS = 'CONTRIBUTIONS',
  USER_MANAGEMENT = 'USER_MANAGEMENT',
  CONTENT_MANAGEMENT = 'CONTENT_MANAGEMENT',
  ANALYTICS_VIEW = 'ANALYTICS_VIEW',
}
