name: Deploy KindSoul Production

on:
  push:
    branches:
      - pre-production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # =========================
      # Deploy to PROD-1
      # =========================
      - name: Deploy to prod-1
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PRE_PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PRE_PRODUCTION_SSH_KEY }}
          script: |
            set -euo pipefail
            echo "Deploying on prod-1"

            cd /var/www/html/KindSoul-F
            git fetch origin
            git checkout pre-production
            git pull origin pre-production

            cat << 'EOF' > .env
            ${{ secrets.ENV_PRE }}
            EOF

            docker build -t front:latest .
            docker stop front || true
            docker rm front || true

            docker run -d \
              --name front \
              -p 8080:80 \
              --restart unless-stopped \
              front:latest

            echo "Waiting for frontend to become healthy..."

            for i in {1..20}; do
              if curl -s -f http://localhost:80 > /dev/null; then
                echo "Frontend is healthy on prod-1"
                exit 0
              fi
              echo "Still waiting..."
              sleep 3
            done

            echo "Frontend failed to start on prod-1"
            exit 1

